name: running test, build image and deploy
on:
    push:
        branches: [main]

jobs:
    unit-test:
        name: running test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-go@v2
              with:
                  go-version: "1.20"
            - name: test
              run: go test -v ./... -cover

    build-image:
        name: build image
        runs-on: ubuntu-latest
        needs: unit-test
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: build image
              run: docker build -t hantzord/cicd-go-app:latest .
            - name: login to docker hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: push image
              run: docker push hantzord/cicd-go-app:latest

    deploy-to-ec2:
        name: deploy to ec2
        runs-on: ubuntu-latest
        needs: build-image
        steps:
            - uses: actions/checkout@v2
            - name: deploy to ec2
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                    cd /home/ec2-user/cicd-go-app
                    docker pull hantzord/cicd-go-app:latest
                    docker run -d -p 8080:8080 hantzord/cicd-go-app:latest

                  